- utils/detectLSPInterface.ts
Somehow, TS checks passed this. 
UP's interfaces are LSP0 SC, so we only check LSP3 on the key-value-store, eg. through SupportedStandards afterwards.
> Resolve unknown interface ID

- shared/config.ts
N/A
Due to high amount of RPC calls gateway.fm is no longer reliable solution as it has limits. Temporarily we switch to our own RPC until we introduce proper optimizations in RPC calls.
> chore: Change RPC

- components/AppNavbar.vue
- shared/config.ts
- tests/e2e/lyx-details.spec.ts
[DEV-8514](https://app.clickup.com/t/2645698/DEV-8514)
Brand click should redirect to `my.universalprofile.cloud`
> fix: Redirect to `my.universalprofile.cloud` when clicking on logo

- app.vue
- types/global.d.ts
[DEV-8767](https://app.clickup.com/t/2645698/DEV-8767)
- expose global web3 object
> feat: Expose global web3 instance

- app.vue
- components/AppNavbar.vue
- components/SendCardProfileSearch.vue
- composables/useBrowserExtension.ts
- composables/useWeb3.ts
- models/asset.ts
- models/base.ts
- models/creator.ts
- models/image.ts
- models/profile.ts
- pages/[profileAddress]/send.vue
- repositories/asset.ts
- repositories/creator.ts
- repositories/image.ts
- repositories/profile.ts
- shared/config.ts
- stores/app.ts
- translations/en_US.json
- types/network.ts
- types/provider.d.ts
- utils/fetchProfile.ts
- utils/getErrorMessage.ts
- utils/getImages.ts
[DEV-8289](https://app.clickup.com/t/2645698/DEV-8289)
- handle network switch from ext
> feat: network switch

- package.json
- shared/config.ts
- yarn.lock
Change to use IPFS proxy in cloudflare.
> fix: Change to ipfs proxy in cloudflare

- components/ProfileCard.vue
- package.json
- translations/en_US.json
- yarn.lock
[DEV-8972](https://app.clickup.com/t/2645698/DEV-8972)
- add copy tooltip
> feat: add profile tooltip

- README.md
Not a big deal but it helps to have the deployment info in the README.
I also deleted the previous GitHub pages deployment.
> docs: add deployment info on README

- utils/fetchLsp3Profile.ts
- utils/validateLsp3Metadata.ts
This adds a compatibility with profiles encoded with `keccak256(bytes)`.
Also add more security for undefined var in the profile JSON which would cause issues on the whole page.
> fix: add fix for bytes verifiableuri + improve error

- .github/workflows/ci.yml
There is this bug when CI is stuck on install.
In a normal working mode, the CI never takes more than 7min to perform. So 15min is double that. We don't need to have 60min timeout. After 10min we know already that something is off.
> chore: set gh action timeout to 15min

- package.json
- yarn.lock
- console is flooded with custom component warnings, apparently `vue` shipped with `nuxt` doesn't pick up the config properly, adding explicit dependency fixes that.
> chore: remove custom component warnings

- app.vue
- tests/unit/utils/validators.spec.ts
- utils/fetchAssets.ts
- utils/fetchLsp3Profile.ts
- utils/fetchProfile.ts
- utils/validators.ts
[DEV-9566](https://app.clickup.com/t/86bx18mt2)
- split fetching keys (LSP3, LSP5, LSP12) so when one fails it won't affect the others
> fix: Profile appear as anonymous when decoding asset key fails

- pages/[profileAddress]/index.vue
[DEV-9563](https://app.clickup.com/t/2645698/DEV-9563)
- owned asset button count should not include LYX balance when it's 0
> fix: Owned assets is incorrect when LYX balance is 0

- components/SendCardAmount.vue
[DEV-9569](https://app.clickup.com/t/2645698/DEV-9569)
- validate decimal places based on the asset `decimals` value
> fix: Limit input length based on asset decimals

- repositories/asset.ts
[DEV-9562](https://app.clickup.com/t/2645698/DEV-9562)
- atm we displayed all tokens from `LSP5` array but we should filter out the one without balance
> fix: display only tokens with balance

- pages/[profileAddress]/lyx-details.vue
- pages/asset/[nftAddress]/tokenId/[tokenId].vue
- pages/asset/[tokenAddress].vue
[DEV-9640](https://app.clickup.com/t/2645698/DEV-9640)
- fix for showing owned balance in LYX details
- small refactors to owned section in assets
> fix: wrong display of LYX balance in detailed view

- utils/fetchProfile.ts
DEV-9892
https://app.clickup.com/t/2645698/DEV-9892
Issue was coming from the profile JSON file, it had {} for the backgroundImage field and the app was expecting a [].
The app needs to be more bullet proof to broken and non valid JSON files.
This is a quick fix but it probably requires more handling.
> fix: error on sort on profile load

- components/AssetAddress.vue
- components/AssetTokenId.vue
- pages/asset/[nftAddress]/tokenId/[tokenId].vue
[DEV-10056](https://app.clickup.com/t/2645698/DEV-10056)
- truncate very long token ids in desktop view so they don't break UI
- add even more truncation in mobile view
> fix: Truncate long token ids

- components/SendCardProfileSearch.vue
[DEV-10239](https://app.clickup.com/t/2645698/DEV-10239)
- since EoA can't be found in index it show "Profile not found" message. But for EOA we should hide it as it's still valid receipent.
> fix: when sending to EOA dropdown overlap the button

- pages/[profileAddress]/send.vue
DEV-10405
Change the force flag based on type of the receiver address, if its an EOA it should be true otherwise it should be false
[LSP7 transaction](https://explorer.execution.mainnet.lukso.network/tx/0xeb05e976015febf0d6241d35b545036ae3f05f94ff7a76a0e23ba41a88b7dc0b)
> fix: allow LSP7 & LSP8 transfers to EOA

- pages/[profileAddress]/index.vue
[DEV-10766](https://app.clickup.com/t/2645698/DEV-10766)
We want to have assets more organized before we introduce some sorting options. Thats why new default sorting will be by `name` instead of the date when it was added to profile.
> feat: change asset to be sorted by name instead of added date

- components/TokenList.vue
- composables/useFilters.ts
- pages/[profileAddress]/index.vue
- shared/enums.ts
- stores/app.ts
- types/filters.ts
[DEV-10979](https://app.clickup.com/t/2645698/DEV-10979)
- adds `assetType=owned|created` query param to select between created and owned assets. This will allow to create more personalized links.
- refactor filters into composition (prepare for next filters)
- when profile has created assets it will be displayed by default (unless there is `assetType` query param in url)
> feat: allow to specify `assetType` filter in the URL

- components/CreationsCarousel.vue
- components/NftCard.vue
- components/TokenListCard.vue
- composables/useToken.ts
- package.json
- utils/__tests__/decodeParameter.spec.ts
- utils/decodeParameter.ts
- yarn.lock
[DEV-11159](https://app.clickup.com/t/2645698/DEV-11159)
Turns out that real problem is that some assets has incorrectly encoded `tokenId` and unhandled exception from the decoder break the UI and carousel too. Issue only happens on first load, once data is cached it pass the check.
Example profiles: 
https://universalprofile.cloud/0xaE4FeE208eB0ed7b3491511059Ba31964314AeCB
https://universalprofile.cloud/0xfa39A2207f1d1C1ceC32502000481F0feF660384
On Safari there is still issue where user can't click on the carousel item to visit details view, it works only with middle slide. This seem to be bug in the carousel it self.
> fix: carousel blocks on  Safari

- domains/grid/components/GridView.vue
- domains/grid/composables/useGrid.ts
- domains/grid/shared/config.ts
- domains/grid/utils/gridLayout.ts
- stores/app.ts
N/A
Added `gridColumnsLarge` to local storage that controls number of columns
> feat: allow to test different grid column size

- domains/grid/components/GridWidget.vue
[DEV-11873](https://app.clickup.com/t/2645698/DEV-11873)
> feat: allow widget selection when not in edit mode

- domains/grid/components/GridWidget.vue
- domains/grid/components/GridWidgetAddContent.vue
- tailwind.config.js
[DEV-11892](https://app.clickup.com/t/2645698/DEV-11892)
> feat: update new content placeholder

- components/AppModal.vue
- components/ProfileCard.vue
- components/__tests__/__snapshots__/ProfileCard.spec.ts.snap
- composables/web3-provider/useBaseProvider.ts
- domains/grid/components/AddWidgetSelection.vue
- domains/grid/components/GridWidget.vue
- translations/en_US.json
[DEV-11930](https://app.clickup.com/t/2645698/DEV-11930)
> feat: grid design adjustments

- app.vue
- components/ProfileView.vue
- domains/grid/components/GridView.vue
- domains/grid/composables/useGrid.ts
- stores/grid.ts
[DEV-11934](https://app.clickup.com/t/2645698/DEV-11934)
- store independently grid temp state for each account
- improve profile tabs display
> fix: handle multiple user sessions for grid

- components/AppNavbar.vue
- components/AppNavbarLanding.vue
- components/AppNavbarProfileDropdown.vue
- components/AppNotFound.vue
- components/AssetAssetsDocument.vue
- components/AssetAssetsOther.vue
- components/AssetImage.vue
- components/BuyLyxCard.vue
- components/DappShowcase.vue
- components/ModalTemplateConnectWallet.vue
- components/NftAssetView.vue
- components/ProfileCardShareUniversalPage.vue
- components/ProfileCardShareUniversalSwaps.vue
- components/TokenAssetView.vue
- components/TokenListCardLyx.vue
- components/__tests__/ProfileCardShareUniversalPage.spec.ts
- components/__tests__/ProfileCardShareUniversalSwaps.spec.ts
- composables/web3-provider/useBrowserExtensionProvider.ts
- domains/graph/components/NftListCardGraph.vue
- domains/graph/components/TokenListCardGraph.vue
- domains/grid/components/GridWidget.vue
- domains/rpc/components/NftListCardRpc.vue
- domains/rpc/components/TokenListCardRpc.vue
- package.json
- pages/[profileAddress]/lyx-details.vue
- pages/contract/[...slug].vue
- pages/index.vue
- yarn.lock
[DEV-11645](https://app.clickup.com/t/2645698/DEV-11645)
- show settings link for non connected users
- refactors `window.open` into `navigateTo`
> feat: settings link for non logged users

- components/AppNavbar.vue
- components/AppNavbarAvatar.vue
- components/AppNavbarLanding.vue
- components/AppNavbarProfileDropdown.vue
[DEV-11941](https://app.clickup.com/t/2645698/DEV-11941)
> feat: mobile nav bar updates

- domains/grid/components/GridFloatingMenu.vue
- domains/grid/components/GridWidget.vue
- domains/grid/components/__tests__/GridFloatingMenu.spec.ts
- domains/grid/composables/useGrid.ts
- stores/app.ts
[DEV-11970](https://app.clickup.com/t/2645698/DEV-11970)
> fix: widget clone issue

- domains/grid/components/AddWidgetBasic.vue
[DEV-11968](https://app.clickup.com/t/2645698/DEV-11968)
> feat: widget instructions update

- components/AppPageLoader.vue
- domains/grid/components/GridFloatingMenu.vue
- domains/grid/components/__tests__/__snapshots__/GridFloatingMenu.spec.ts.snap
- pages/settings/__tests__/__snapshots__/index.spec.ts.snap
- pages/settings/data-provider/__tests__/__snapshots__/index.spec.ts.snap
[DEV-11980](https://app.clickup.com/t/2645698/DEV-11980)
> feat: floating menu adjustments

- domains/grid/components/GridFloatingMenu.vue
- domains/grid/components/__tests__/__snapshots__/GridFloatingMenu.spec.ts.snap
- package.json
- yarn.lock
[DEV-11987](https://app.clickup.com/t/2645698/DEV-11987)
> feat: update add grid icon

- app.vue
- nuxt.config.ts
- package.json
- service-worker/sw.ts
- tsconfig.json
https://app.clickup.com/t/2645698/DEV-11966
provide a new boolean called swHasUpgrade using provide('swHasUpgrade', hasUpgrade)
the value will be set if an upgrade is detected during the initial page load. The upgrade will be allowed,
but the new version will not be initialized such that we can notify the user they can reload to get an upgrade
next time. It should automatically upgrade on the next full navigation to another page anyways.
> feat: Add swHasUpgrade but prevent auto reload.

- domains/grid/components/GridWidgetIframe.vue
- domains/grid/components/GridWidgetInstagram.vue
- domains/grid/components/GridWidgetX.vue
- domains/grid/schema/xWidgetSchema.ts
[DEV-11887](https://app.clickup.com/t/2645698/DEV-11887)
> fix: iframe refresh on resize
