lukso-network/universalprofile.cloud

app.vue
components/connectOrInstallButton.vue
components/navbar.vue
composables/useBrowserExtension.ts
pages/index.vue
stores/connection.ts
stores/profile.ts
translations/en_US.json

[DEV-6525](https://app.clickup.com/t/2645698/DEV-6525)
- detect properly installed extension
- redirect to profile from landing when user is connected
- fix navbar issues with missing links
- fix navbar logo redirect

fix: Landing page and navbar component fixes

---

composables/useBrowserExtension.ts
shared/config.ts

N/A
Use `window.lukso` instead default `window.ethereum`

fix: change injected provider

---

nuxt.config.ts

[DEV-8204](https://app.clickup.com/t/2645698/DEV-8204)
Use correct wallet domain for plausible.

fix: update plausible domain

---

components/profile.vue
package.json
yarn.lock

[DEV-8028](https://app.clickup.com/t/2645698/DEV-8028)
Show new profile `hero` card.

feat: New profile hero

---

composables/useBrowserExtension.ts

N/A
When provider disconnects we should reload dApp.

fix: Refresh app after disconnecting provider

---

components/asset-images.vue
pages/[profileAddress]/token/[tokenAddress].vue

N/A
- apparently test dApp post empty array of images so adding check for this
- hide links card when none

fix: Fix for missing images or links

---

components/send-draft.vue

https://app.clickup.com/t/862kcvccu
Add validation to amount field.

feat: Add amount field validations

---

package.json
yarn.lock

fix: Update social links

---

components/profile.vue

N/A
Copy UP address from hero card.

feat: Allow to copy hero address

---

components/profile.vue

N/A
Profile hero miss identicon.

fix: Add missing identicon in profile hero

---

pages/[profileAddress]/nft/[nftAddress]/tokenId/[tokenId].vue
pages/[profileAddress]/token/[tokenAddress].vue

N/A
As discussed with Tim we hide standard info since it doesn't give any value atm.

fix: hide standard info

---

.github/workflows/artifacts.yml
README.md

N/A
- fix some of job titles 
- rename `build` -> `lint` since it's only lint there and build is in other place
- add release readme

chore: release adjustments

---

app.vue
layouts/default.vue
utils/setupViewedAssets.ts
utils/setupViewedProfile.ts

fix: back button glitch

---

.github/workflows/release.yml

chore: change branch in RP

---

components/profile.vue
translations/en_US.json

fix: display properly anonymous account

---

README.md

chore: resolve main conflicts

---

components/AssetLinks.vue

[DEV-8256](https://app.clickup.com/t/2645698/DEV-8256)
Separate links.

fix: Separate links

---

pages/[profileAddress]/nft/[nftAddress]/tokenId/[tokenId].vue

[DEV-8259](https://app.clickup.com/t/2645698/DEV-8259)
- remove count from NFT card
- fix owned count

style: change NFT details

---

components/ProfileDetails.vue
pages/[profileAddress]/index.vue
types/enums.ts

[DEV-7994](https://app.clickup.com/t/2645698/DEV-7994)
Show profile details when `referrer` query param is `indexer`. 
Example: `https://wallet.universalprofile.cloud/0x64DE43F67e533b59A5791E6aB1e5a80626E10710?referrer=indexer`

feat: Show profile details

---

composables/useBrowserExtension.ts

[DEV-8318](https://app.clickup.com/t/2645698/DEV-8318)
Fix issue when profile didn't fetch assets after connecting.

fix: Refresh tokens after connecting

---

site.meta.json

[DEV-8535](https://app.clickup.com/t/2645698/DEV-8535)
Update title

fix: Update meta title

---

.github/auto_assign.yaml
.github/workflows/review.yaml
tests/e2e/lyx-details.spec.ts

chore: Add auto assign action

---

.env.example
components/AppAvatar.vue
components/SendCardAmount.vue
components/SendCardDraft.vue
components/SendCardHeader.vue
components/SendCardProfileSearch.vue
composables/useErc725.ts
nuxt.config.ts
package.json
pages/[profileAddress]/send.vue
shared/config.ts
translations/en_US.json
types/profile.ts
yarn.lock

[DEV-8251](https://app.clickup.com/t/2645698/DEV-8251)
[DEV-8385](https://app.clickup.com/t/2645698/DEV-8385)
- adds profile search to send view
- add keyboard control of search options

feat: search profiles

---

components/AppFooter.vue
package.json
yarn.lock

[DEV-8647](https://app.clickup.com/t/2645698/DEV-8647)
- update footer logo
- change Twitter link

feat: Update footer

---

components/AppNavbar.vue
shared/config.ts
translations/en_US.json

Ticket ID
[DEV-8621](https://app.clickup.com/t/2645698/DEV-8621)
[DEV-8646](https://app.clickup.com/t/2645698/DEV-8646)
Description
Add discovery link to header
Changed navbar brand onClick to point to up.cloud

feat(DEV-8621): add discovery link to header

---

package.json
yarn.lock

[DEV-8668](https://app.clickup.com/t/2645698/DEV-8668)
Update github logo on footer

fix(DEV-8668): update github logo on footer

---

app.vue
composables/useBrowserExtension.ts
utils/loadViewedAssets.ts
utils/loadViewedProfile.ts

N/A
- refactor `onMounted` hook so it look bit cleaner

chore: Refactor onMounted hook

---

components/AppLoader.vue
composables/useBrowserExtension.ts
pages/[profileAddress]/index.vue
pages/[profileAddress]/lyx-details.vue
pages/[profileAddress]/nft/[nftAddress]/tokenId/[tokenId].vue
pages/[profileAddress]/send.vue
pages/[profileAddress]/token/[tokenAddress].vue
pages/index.vue
translations/en_US.json
utils/getErrorMessage.ts

[DEV-8761](https://app.clickup.com/t/2645698/DEV-8761)
- rework error handling
- show more accurate message when user try to send LYX to himself 
- fix page loader

feat: improve error handling

---

components/AssetCreator.vue
components/NftListCard.vue
components/SendCardDraft.vue
components/profile.vue
composables/useErc725.ts
pages/[profileAddress]/nft/[nftAddress]/tokenId/[tokenId].vue
types/assets.ts
types/profile.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp4Creators.ts

[DEV-8754](https://app.clickup.com/t/2645698/DEV-8754)
- make two side creator verification
- support for multiple creators for an asset

feat: verify LSP4 creators

---

translations/en_US.json

DEV-8915
https://app.clickup.com/t/2645698/DEV-8915

fix: remove plural from Universal Profiles wallet landing title

---

pages/[profileAddress]/send.vue
utils/fetchLsp3Profile.ts
utils/fetchProfile.ts
utils/updateLyxBalance.ts

[DEV-8874](https://app.clickup.com/t/2645698/DEV-8874)
- update profile balance on every load to get latest value

fix: update LYX balance

---

components/AppFooterNetworkSelect.vue
models/image.ts
utils/fetchLSP7Assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp3Profile.ts
utils/getImages.ts
utils/validateLSP4Metadata.ts
utils/validateLsp3Metadata.ts

[DEV-8949](https://app.clickup.com/t/2645698/DEV-8949)
- add support for new image metadata format

fix: missing images

---

pages/[profileAddress]/lyx-details.vue
shared/config.ts
types/network.ts

[DEV-8873](https://app.clickup.com/t/2645698/DEV-8873)
- show correct total token supply for LYX token

fix: LYX total token supply

---

package.json
yarn.lock

N/A
- update component library that fix issue in button styling

fix: nav button styling

---

README.md

chore: fix main

---

shared/config.ts

- addressing review comment from https://github.com/lukso-network/wallet.universalprofile.cloud/pull/135#pullrequestreview-1722342772

chore: calculate value in WEI

---

README.md
components/AppFooterNetworkSelect.vue
models/image.ts
package.json
pages/[profileAddress]/lyx-details.vue
pages/[profileAddress]/send.vue
shared/config.ts
types/network.ts
utils/fetchLSP7Assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp3Profile.ts
utils/fetchProfile.ts
utils/getImages.ts
utils/updateLyxBalance.ts
utils/validateLSP4Metadata.ts
utils/validateLsp3Metadata.ts
yarn.lock

chore: Merge to main 2

---

.github/workflows/ci.yml

fix: Add inline builds for testing

---

.github/workflows/ci.yml
package.json
shared/config.ts
yarn.lock

- chore: Merge to main (#140)
- chore: calculate value in WEI (#136)
- fix: Add inline builds for testing (#142)
- fix: Repair build by removing postinstall (#144)

fix: Merge to main

---

utils/fetchLSP7Assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp3Profile.ts
utils/getImages.ts

- improve image selection for given size

chore: refactor image selection

---

translations/en_US.json

fix: typo in nav `discover` button

---

components/ProfileDetails.vue

[DEV-8809](https://app.clickup.com/t/2645698/DEV-8809)
- fix spacing above tags

fix: adjust tags spacing

---

components/SendCardDraft.vue

[DEV-8240](https://app.clickup.com/t/2645698/DEV-8240)
- add back button in send step

feat: add back button to send page

---

models/asset.ts
models/profile.ts
utils/fetchLSP7Assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp3Profile.ts
utils/fetchLsp4Creators.ts
utils/fetchProfile.ts
utils/getImages.ts
utils/validateLSP4Metadata.ts

[DEV-9024](https://app.clickup.com/t/2645698/DEV-9024)
- re-fetch profile if  `hash`/`verification.data` has changed

fix: re-fetch profile if it's updated

---

models/asset.ts
repositories/asset.ts
utils/fetchLSP7Assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp3Profile.ts
utils/fetchLsp4Metadata.ts
utils/fetchLsp8Metadata.ts
utils/fetchProfile.ts

- update profile received and issued asset arrays
- fetch asset only if it's hash has changed

fix: asset hash check

---

components/AppNavbar.vue
components/SendCardSuccess.vue
pages/[profileAddress]/send.vue
stores/app.ts

[DEV-8265](https://app.clickup.com/t/2645698/DEV-8265)
- show simplified navbar when user is sending asset 
- fix issue when user stayed on send page when disconnected

feat: show simplified navbar when sending assets

---

package.json
yarn.lock

[DEV-8766](https://app.clickup.com/t/2645698/DEV-8766)
- pull latest component library with fix

fix: prevent window scroll when using arrow keys in dropdowns

---

package.json
yarn.lock

[DEV-8458](https://app.clickup.com/t/2645698/DEV-8458)
- prevent window scroll when mobile menu is open

fix: block window scroll when mobile menu is open

---

components/ProfileCard.vue

- make smaller address in mobile view

fix: address size in mobile view

---

composables/useBrowserExtension.ts
pages/[profileAddress]/send.vue

N/A
- it's better UX if network check happen before call

fix: do network check before call

---

app.vue
shared/config.ts
stores/app.ts
types/network.ts

[DEV-9059](https://app.clickup.com/t/86bwgg7y0)
- switch to Testnet when `network=testnet` query param is present

fix: trigger network switch based on query param

---

components/SendCardDraft.vue

- fix wrong position of back button

fix: arrow alignment

---

components/AppNavbar.vue
components/AppNavbarProfileDropdown.vue
utils/activePage.ts

- highlight link for active page

feat: change link style of active page

---

package.json
yarn.lock

chore: update web components

---

.prettierrc
package.json
yarn.lock

chore: Add plugin to auto format Tailwind class order

---

components/AppNavbar.vue
shared/config.ts
utils/externalUrls.ts

[DEV-9082](https://app.clickup.com/t/2645698/DEV-9082)
- pass network id with query params

feat: pass network with params

---

README.md

--
This will help to document things

docs: add network switch info in README

---

README.md
app.vue
shared/config.ts
types/network.ts

Will release the network switch mainnet fix

chore: release

---

app.vue
components/AppFooterNetworkSelect.vue
types/network.ts

fix: reload page properly when network query param is present

---

package.json
yarn.lock

https://app.clickup.com/t/2645698/DEV-9377
DEV-9377
Support `VerifiableURI`

chore: update erc725.js to v0.22.0

---

.github/workflows/ci.yml
package.json
utils/fetchLsp3Profile.ts
utils/validateLsp3Metadata.ts
yarn.lock

[PROD] - Release to prod

---

package.json
utils/detectStandard.ts
yarn.lock

[DEV-9389](https://app.clickup.com/t/2645698/DEV-9389)
- add support for old interfaces for LSP7/8

feat: Support old interfaces ID for LSP7/8

---

components/NftListCard.vue
repositories/asset.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp8Metadata.ts
utils/validateLSP4Metadata.ts

[DEV-9483](https://app.clickup.com/t/2645698/DEV-9483)
- support for new LSP8 keys: `LSP8TokenIdFormat` and `LSP8TokenMetadataBaseURI `

fix: Support for LSP8

---

models/asset.ts
repositories/asset.ts
utils/fetchLSP8Assets.ts

[DEV-9511](https://app.clickup.com/t/86bwzzpng)
- introduce `owner` param for LSP8 tokens

fix: Add owner to LSP8 tokens

---

components/AssetOwnInfo.vue
pages/[profileAddress]/lyx-details.vue
pages/asset/[nftAddress]/tokenId/[tokenId].vue
pages/asset/[tokenAddress].vue
translations/en_US.json

[DEV-9512](https://app.clickup.com/t/2645698/DEV-9512)
- NFT details shown owner info incorrectly

fix: Show correct owner info in NFT details

---

models/asset.ts
types/assets.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp8Metadata.ts
utils/validateLSP4Metadata.ts

[DEV-9520](https://app.clickup.com/t/2645698/DEV-9520)
- add support for LSP4 metadata for LSP8
- use `LSP8TokenMetadataBaseURI` as fallback 
- add `null` checks to verification object

fix: chill whales NFT are not displayed in wallet

---

utils/urlResolver.ts

[DEV-9505](https://app.clickup.com/t/2645698/DEV-9505)
- replace `at` with `slice` that is supported by mobile Safari browser

fix: Replace `at` with `slice`

---

shared/config.ts

chore: Switch RPC to gateway.fm

---

utils/getImages.ts

[DEV-9502](https://app.clickup.com/t/2645698/DEV-9502)
- some image `url` contain `base64` encoded images. In such cases we put encoded image directly into cache.

fix: handle base64 image urls

---

components/AssetLinks.vue

- fix how multiple links are displayed

fix: display of multiple asset links

---

shared/config.ts

chore: Switch Testnet to `gateway.fm`

---

app.vue

- adds return statements so we don't go further when address is not correct

fix: Don't proceed when address is invalid

---

repositories/asset.ts
utils/getImages.ts

[DEV-9575](https://app.clickup.com/t/2645698/DEV-9575)
- when image fetching fails it interrupt loading assets in the modal

fix: user can't select owned asset while sending

---

shared/config.ts

[DEV-9503](https://app.clickup.com/t/2645698/DEV-9503)
- switch to `LYX` for getting FIAT price

feat: Use LYX token to compare

---

utils/fetchLsp8Metadata.ts

[DEV-9687](https://app.clickup.com/t/86bx3y273)
- looks like they adding white space in ipfs link and that makes the url invalid (probably typo on their side)

fix: lowercase decoded token id

---

components/AppNavbar.vue
translations/en_US.json

fix: remove buy lyx button in navbar

---

components/AppFooter.vue
translations/en_US.json

https://app.clickup.com/t/2645698/DEV-9813

fix: update FAQ link and remove need help

---

app.vue
plugins/algolia.ts

[DEV-9891](https://app.clickup.com/t/2645698/DEV-9891)
- fixes profile check when user come from testnet indexer to wallet

fix: when coming from universalprofile.cloud (testnet) and wallet was previously on mainnet, we get a 404

---

components/ModalTemplateSelectAssets.vue
components/NftListCard.vue
models/asset.ts
repositories/asset.ts
utils/assetChecks.ts
utils/fetchLSP8Assets.ts
utils/fetchLsp7Asset.ts

[DEV-8799](https://app.clickup.com/t/2645698/DEV-8799)
- show LSP7 collectible as NFT card, this doesn't include new card look yet (there is other ticket to address this)
- fix for showing assets in send modal

feat: differentiate LSP7 token and LSP7 collectible

---

package.json
utils/fetchLSP8Assets.ts
utils/fetchLsp7Asset.ts
utils/fetchProfile.ts
utils/getHash.ts
utils/getImages.ts
utils/validateLSP4Metadata.ts
yarn.lock

[DEV-9989](https://app.clickup.com/t/86bxcdzz9)
- change how unique image ids are made to not rely to much on `verification` object

fix: Make image id from url

---

repositories/asset.ts

[DEV-9983](https://app.clickup.com/t/2645698/DEV-9983)
- since now LSP7 can be as collectible NFT we need to do balance check for collectibles

fix: hide tokens that has `0` balance

---

utils/getImages.ts

[DEV-10016](https://app.clickup.com/t/2645698/DEV-10016)
- atm image link to asset is broken as first hash was made from unresolved url

fix: Resolve url before hashing

---

models/profile.ts
utils/fetchProfile.ts

fix: UP LSPStandard prop

---

models/profile.ts
utils/fetchProfile.ts

[DEV-10066](https://app.clickup.com/t/2645698/DEV-10066)
- add fallback support to legacy `type` field

fix: Add `type` field check for profile

---

utils/fetchProfile.ts

[DEV-10038](https://app.clickup.com/t/2645698/DEV-10038)
- add RPC check for profile when not returned by indexer

fix: Add RPC check for non indexed profiles

---

app.vue
components/AppNavbar.vue
components/AppNavbarMobileSearch.vue
components/AppNavbarProfileSearch.vue
components/AppPageLoader.vue
components/AssetAttributes.vue
components/AssetCreators.vue
components/AssetLinks.vue
components/AssetOwnInfo.vue
components/SendCardProfileSearch.vue
components/TokenListCard.vue
components/TokenListLyxCard.vue
models/profile.ts
package.json
pages/[profileAddress]/buy-lyx.vue
pages/[profileAddress]/index.vue
pages/[profileAddress]/lyx-details.vue
pages/asset/[nftAddress]/tokenId/[tokenId].vue
pages/asset/[tokenAddress].vue
stores/app.ts
types/image.ts
yarn.lock

[DEV-10060](https://app.clickup.com/t/2645698/DEV-10060)
- adjust screens on mobile

fix: mobile adjustments

---

repositories/asset.ts

https://app.clickup.com/t/2645698/DEV-10178
- this is quick fix to show created assets
- it doesn't do verification check, TBD with Tim if this require design change

fix: Show created assets

---

translations/en_US.json

Changed Transak description to "Transak provides leading Web3 on-ramp services, enabling users from over 180 countries to access $LYX through various fiat payment methods."

fix: quick translation fix for Transak

---

composables/useToken.ts
service-worker/sw.ts
utils/fetcher.ts

Fix the new 308 redirect that universal.page has put on their name service.

fix: Universal.page new 308 redirect

---

composables/useNetworkConfig.ts

Seem like Thirdweb some low limit so for time being we swap to our node.

fix: Change node to LUKSO

---

composables/useAsset.ts
composables/useLocalStorage.ts
composables/useToken.ts
utils/queryFunctions.ts

Fix: Simplify result indexes by introducing a null query.

fix: Refactor by introducing a null query to simplify results indexes.

---

components/AssetImage.vue
composables/useLocalStorage.ts
types/contract.ts
utils/assetChecks.ts
utils/paddedToAddress.ts

[DEV-10487](https://app.clickup.com/t/86by28uyz)
- fix issue with connection because of missing `return` 
- small refactors

fix: user connection issue

---

composables/useProfile.ts
composables/useProfileLink.ts
types/profile.ts

Add profile link resolver to resolve link and resolved into Profile structure.
```js
{
...rest,
link: https://m.profile.link/RESOLVED
resolved: RESOLVED
}
```

feat: Add profile.link resolver access (currently m.profile.link)

---

composables/useProfileAssets.ts

[DEV-10517](https://app.clickup.com/t/2645698/DEV-10517)
- fix issue in how we check that assets is received/issued

fix: Correctly check for created/issued assets

---

components/ProfileCardShareLink.vue
components/TokenListCard.vue
components/TokenListLyxCard.vue
composables/useProfile.ts
composables/useWeb3.ts
nuxt.config.ts
package.json
utils/processMetadata.ts
utils/queryFunctions.ts
yarn.lock

[DEV-10561](https://app.clickup.com/t/86by6mkbv)
- resize fixed
- fix special characters in description

fix: Repair resizing

---

composables/useProfileAssets.ts
composables/useToken.ts

[DEV-10585](https://app.clickup.com/t/2645698/DEV-10585)
- fix issue with duplicated assets

fix: duplicated assets 

---

components/ProfileCardShareLink.vue
components/ProfileDetails.vue
tailwind.config.js
utils/sleep.ts

[DEV-10557](https://app.clickup.com/t/2645698/DEV-10557)
- add animation to profile link
- fix icon size issue

feat: animate profile link

---

components/AppNavbarProfileSearch.vue
components/AssetDescription.vue
components/ProfileDetails.vue
components/SendCardAmount.vue
composables/useIntl.ts
composables/useNetworkConfig.ts
package.json
stores/send.ts
utils/__tests__/truncate.spec.ts
utils/truncate.ts
vitest.config.ts
yarn.lock

[DEV-10679](https://app.clickup.com/t/2645698/DEV-10679)
- allow to paste amount from clipboard 
- shorten unit display for long digits
- allow break lines in descriptions
- add LUKSO Testnet RPC

fix: send improvements

---

components/AssetName.vue
components/AssetOwnInfo.vue
components/NftAssetView.vue
components/NftListCard.vue
components/SelectAssetsLyx.vue
components/SelectAssetsToken.vue
components/SendCardAmount.vue
components/SendCardDraft.vue
components/SendCardPending.vue
components/TokenAssetView.vue
components/TokenListCard.vue
utils/__tests__/truncate.spec.ts
utils/truncate.ts

[DEV-10678](https://app.clickup.com/t/2645698/DEV-10678)
- add support for long token names and symbols

fix: Support for long names

---

components/ModalTemplateAssetImage.vue

[DEV-10625](https://app.clickup.com/t/2645698/DEV-10625)
- make sure image preview is displayed properly in different screen sizes

fix: Fix issue with image sizing

---

components/AssetImagesList.vue
composables/useImages.ts
utils/getImages.ts

[DEV-10549](https://app.clickup.com/t/2645698/DEV-10549)
- resolves problem with infinite call loop for image HEAD

fix: issue with infinite call for image HEAD

---

components/AssetImage.vue

[DEV-10777](https://app.clickup.com/t/2645698/DEV-10777)
Text was not displayed due to width being calculated before image was fully rendered.

fix show missing image text

---

components/AppNavbar.vue
components/AppNavbarProfileDropdown.vue
components/SendCardDraft.vue
components/SendCardSuccess.vue
composables/useBrowserExtension.ts
composables/useProtectedRoute.ts
pages/[profileAddress]/send.vue
pages/index.vue
pages/settings/index.vue
pages/settings/missing-assets/[assetAddress]/add.vue
pages/settings/missing-assets/[assetAddress]/success.vue
pages/settings/missing-assets/index.vue
shared/routes.ts

[DEV-10810](https://app.clickup.com/t/2645698/DEV-10810)
- Remove connected profile address from all settings urls so it allows to easy link to settings pages
- Refactor protected routes check into `useProtectedRoute` composition
- Refactor `profileRoute` to handle `undefined` address as a param

feat: remove profile address from settings urls

---

pages/[profileAddress]/buy-lyx.vue
utils/externalUrls.ts

[DEV-10794](https://app.clickup.com/t/2645698/DEV-10794)
- change LUKSO logo used in Ramp
- hide buy LYX on Ramp until official announcement

chore: hide Ramp feature

---

components/AppNavbar.vue
components/AppNavbarLanding.vue
components/AppNavbarProfileDropdown.vue
components/SendCardSuccess.vue
pages/[profileAddress]/send.vue
stores/app.ts
translations/en_US.json

[DEV-10927](https://app.clickup.com/t/2645698/DEV-10927)
- adjust navbar to new merged apps
- allow to connect profile from index
- display full navbar when sending assets

feat: navbar changes

---

.gitignore
components/TokenAssetView.vue

[DEV-10956](https://app.clickup.com/t/2645698/DEV-10956)
- Show creators in LSP7 token details view
- Ignore VS Code workspace files

feat: show LSP7 token creators

---

site.meta.json

[DEV-10968](https://app.clickup.com/t/86bytvr1p)
Remove "Wallet" word from page title and update description.

fix: update site meta

---

components/NftListCard.vue
components/SendCardDraft.vue

[DEV-10966](https://app.clickup.com/t/2645698/DEV-10966)
When sending LSP8 asset we want to show more token related information rather then amount.

feat: Change dropdown when sending LSP8

---

components/SendCardProfileSearch.vue
composables/useBrowserExtension.ts

[DEV-10961](https://app.clickup.com/t/2645698/DEV-10961)
After pasting valid address and loosing focus on the input field we already check for profile.

fix: Select profile when receiver input loose it's focus

---

components/AssetAssets.vue
components/AssetAssetsDocument.vue
package.json
pages/settings/missing-assets/[assetAddress]/add.vue
shared/routes.ts
utils/__tests__/truncate.spec.ts
utils/browserInfo.ts
utils/checkNetwork.ts
utils/processMetadata.ts
utils/queryFunctions.ts
utils/tokenConversionWithDecimals.ts
utils/urlResolver.ts
utils/validators.ts

N/A
- include Biome check in lint script
- fix reported Biome issues

chore: Add biome to lint script and fix issues

---

components/CreationsCarousel.vue
components/NftAssetView.vue
components/NftCard.vue
nuxt.config.ts
package.json
pages/[profileAddress]/index.vue
shared/routes.ts
tailwind.config.js
translations/en_US.json
utils/validateLspMetadata.ts
yarn.lock

[DEV-11079](https://app.clickup.com/t/2645698/DEV-11079)
Adds carousel for created assets.

feat: Carousel for created assets

---

components/AssetImagesList.vue
components/CreationsCarousel.vue
components/NftCard.vue
components/NftListCard.vue
composables/useFilters.ts

[DEV-11159](https://app.clickup.com/t/2645698/DEV-11159)
- make fixed height to carousel images
- change image size on mobile for collection card
- fix position of the image in image thumb
- set default `assetType` filter to owned assets

fix: images in carousel don't have same height

---

.env.example
.github/workflows/ci.yml
components/ProfileCardSmall.vue
components/ProfileShowcase.vue
nuxt.config.ts
package.json
queries/profileShowcaseQuery.gql
types/profile.ts
yarn.lock

[DEV-11235](https://app.clickup.com/t/86bz8r9ha)
- refactor profile showcase to use GraphQL instead of Algolia
- remove Algolia

feat: Use GraphQL indexer for profile showcase

---

components/AppNavbarProfileSearch.vue
components/SendCardDraft.vue
components/SendCardProfileSearch.vue
components/__tests__/AppNavbarProfileSearch.spec.ts
components/__tests__/__snapshots__/AppNavbarProfileSearch.spec.ts.snap
queries/profileSearchQuery.gql
stores/send.ts

[DEV-10864](https://app.clickup.com/t/2645698/DEV-10864)
Replace Algolia with GraphQL to search profiles.

feat: Use GraphQL for profile search

---

components/AppNavbarProfileSearch.vue
components/SendCardProfileSearch.vue
domains/graph/components/AssetShowcaseGraph.vue
domains/graph/components/ProfileShowcaseGraph.vue
domains/graph/composables/useProfileAssetsGraph.ts
domains/graph/composables/useProfileGraph.ts
domains/graph/composables/useProfileHoldsGraph.ts
queries/assetShowcaseQuery.gql
queries/profileAssetsQuery.gql
queries/profileHoldsQuery.gql
queries/profileQuery.gql
queries/profileSearchQuery.gql
queries/profileShowcaseQuery.gql

N/A
Use aliases for queries to make JS friendly variable names.

chore: Query aliases

---

components/AssetOwnInfo.vue
components/MissingAssetPreviewItem.vue
components/ModalTemplateSelectAssets.vue
components/NftAssetView.vue
components/SelectAssetsLyx.vue
components/SelectAssetsToken.vue
components/SendCardAmount.vue
components/SendCardDraft.vue
components/SendCardSuccess.vue
components/TokenAssetView.vue
components/TokenListLyxCard.vue
composables/useLyxToken.ts
domains/graph/components/AssetShowcaseItemGraph.vue
domains/graph/components/NftListCardGraph.vue
domains/graph/components/ProfileViewGraph.vue
domains/graph/components/TokenListCardGraph.vue
domains/graph/composables/useAssetGraph.ts
domains/graph/composables/useProfileAssetsGraph.ts
domains/graph/composables/useProfileHoldsGraph.ts
domains/graph/utils/createAssetObject.ts
domains/rpc/components/NftListCardRpc.vue
domains/rpc/components/ProfileViewRpc.vue
domains/rpc/components/TokenListCardRpc.vue
pages/[profileAddress]/lyx-details.vue
utils/__tests__/assetChecks.spec.ts
utils/__tests__/tokenConversionWithDecimals.spec.ts
utils/assetChecks.ts
utils/tokenConversionWithDecimals.ts

N/A
- Add util to check and get balance
- Add util to check for supported asset

feat: Update balance checks

---

app.vue
stores/web3.ts

[DEV-11324](https://app.clickup.com/t/2645698/DEV-11324)
Expose web3 instance in global scope regardless if browser extension is installed or not.

feat: expose web3 instance in global scope

---

components/SendCardDraft.vue
domains/graph/composables/useAssetGraph.ts

[DEV-11199](https://app.clickup.com/t/2645698/DEV-11199)
- add loading states in send view
- improve `isLoading` logic for asset

fix: improve asset load in send

---

components/AppLinks.vue
components/AssetLinks.vue
components/LinkButton.vue
components/ProfileDetails.vue
components/__tests__/AppLinks.spec.ts
components/__tests__/LinkButton.spec.ts
components/__tests__/__snapshots__/AppLinks.spec.ts.snap
components/__tests__/__snapshots__/LinkButton.spec.ts.snap
package.json
types/asset.ts
utils/__tests__/socialLinkParser.spec.ts
utils/socialLinkParser.ts
yarn.lock

[DEV-11338](https://app.clickup.com/t/2645698/DEV-11338)
Detect social media links and replace them with icons.

feat: social media buttons

---

components/AssetAssets.vue
components/AssetAssetsItem.vue
components/AssetAssetsWrapper.vue
components/AssetImagesList.vue
utils/assetFileComponent.ts

[DEV-11325](https://app.clickup.com/t/2645698/DEV-11325)
Move 3D files to images section.

feat: show 3D files in images section

---

domains/graph/utils/createAssetObject.ts
queries/tokenFragment.gql
types/asset.ts

[DEV-11388](https://app.clickup.com/t/2645698/DEV-11388)
- read formatted token id from indexer

feat: Use formatted token id from indexer

---

queries/assetFragment.gql
queries/basicAssetFragment.gql
queries/tokenFragment.gql

[DEV-11392](https://app.clickup.com/t/2645698/DEV-11392)
Fixes order of asset images.

fix: Wrong order in asset `images`

---

pages/index.vue

[DEV-11413](https://app.clickup.com/t/2645698/DEV-11413)
Remove horizontal scrollbar that appears in mobile version.

fix: Remove horizontal scrollbar in mobile

---

components/CollectionView.vue
package.json
yarn.lock

[DEV-11340](https://app.clickup.com/t/2645698/DEV-11340)
Wrap filter selection chips.

fix: wrap filter chips

---

domains/graph/components/ProfileAssetsGraph.vue
domains/graph/components/ProfileViewGraph.vue

[DEV-10134](https://app.clickup.com/t/2645698/DEV-10134)
- fix issue with selecting creators without name
- fix spacing between filter chips
- fix spacing between filters and creations showcase

fix: filter issues

---

pages/[profileAddress]/buy-lyx.vue

[DEV-11450](https://app.clickup.com/t/2645698/DEV-11450)
Enable Ramp integration.

feat: enable Ramp

---

components/ProfileCard.vue
components/__tests__/ProfileCard.spec.ts
components/__tests__/__snapshots__/ProfileCard.spec.ts.snap
package.json
pages/[profileAddress]/index.vue
yarn.lock

[DEV-11478](https://app.clickup.com/t/2645698/DEV-11478)
Redesing profile card.

feat: new profile card

---

components/FollowButton.vue
components/ProfileCard.vue
components/__tests__/FollowCounters.spec.ts

[DEV-11481](https://app.clickup.com/t/2645698/DEV-11481)
- update follower list on follow/unfollow.
- fix lint

fix: following list update

---

pages/settings/index.vue
stores/app.ts

[DEV-10827](https://app.clickup.com/t/2645698/DEV-10827)
- set default fetching method to RPC
- hide switch option in settings

feat: default to RPC

---

components/SendCardProfileSearch.vue

[DEV-11529](https://app.clickup.com/t/2645698/DEV-11529)
We should allow to paste valid addresses even if they are not indexed yet. They will appear and behave like entering EoA.

fix: allow to select non indexed profile

---

components/SendCardProfileSearch.vue

[DEV-11529](https://app.clickup.com/t/2645698/DEV-11529)
Add missing address check when user type profile name.

fix: add address check

---

domains/graph/components/ProfileViewGraph.vue
domains/rpc/components/ProfileViewRpc.vue
domains/rpc/composables/useProfileAssetsRpc.ts
utils/__tests__/assetChecks.spec.ts
utils/assetChecks.ts
yarn.lock

[DEV-11487](https://app.clickup.com/t/2645698/DEV-11487)
Verify creators of the asset.

fix: verify created assets

---

translations/en_US.json

fix: fix wrong translation

---

components/AppAvatar.vue
components/ProfileCardSmall.vue

https://app.clickup.com/t/2645698/DEV-11560

fix: add address with username in send page

---

components/FollowButton.vue

[DEV-11563](https://app.clickup.com/t/2645698/DEV-11563)
We decided to not update UI before TX finishes.

fix: remove optimistic UI and wait for TX to be completed

---

components/FollowCounters.vue
composables/useFollowingSystem.ts
types/profile.ts

[DEV-11586](https://app.clickup.com/t/2645698/DEV-11586)
Add loading flag only for counters.

fix: counters load

---

domains/graph/components/ProfileAssetsGraph.vue

[DEV-11477](https://app.clickup.com/t/2645698/DEV-11477)
Fix issue when user could select same filter multiple times.

fix: allow to select filter only once

---

components/FollowButton.vue
composables/useFollowingSystem.ts

[DEV-11587](https://app.clickup.com/t/2645698/DEV-11587)
Update follower count after receiving transaction hash.

feat: update follower count after receiving transaction hash

---

utils/__tests__/assetChecks.spec.ts
utils/assetChecks.ts

[DEV-11585](https://app.clickup.com/t/2645698/DEV-11585)
Fix missing LSP7 collectibles in profile view.

fix: collectibles are missing

---

domains/graph/components/ProfileAssetsGraph.vue

[DEV-11589](https://app.clickup.com/t/2645698/DEV-11589)

fix: hide LYX card on creator filter

---

composables/useFilters.ts
domains/graph/components/ProfileViewGraph.vue

[DEV-11588](https://app.clickup.com/t/2645698/DEV-11588)
Reset filters when user navigate between tokens and collectibles.

feat: reset filters on tab switch

---

queries/profileSearchQuery.gql

[DEV-11348](https://app.clickup.com/t/2645698/DEV-11348)
Use more "smart" search for profiles.

feat: use new profile search

---

domains/graph/components/ProfileViewGraph.vue

[DEV-11591](https://app.clickup.com/t/2645698/DEV-11591)

feat: select tab based on the asset counts

---

domains/graph/components/ProfileAssetsGraph.vue
package.json
yarn.lock

[DEV-11590](https://app.clickup.com/t/2645698/DEV-11590)
When user hit escape key while searching we clear the input field.

feat: clear search on escape

---

composables/useNetworkConfig.ts
pages/settings/data-provider/__tests__/__snapshots__/index.spec.ts.snap
pages/settings/data-provider/__tests__/index.spec.ts

https://app.clickup.com/t/2645698/DEV-11621
Add mainnet contract for follower system.

feat: mainnet contract for follower system

---

nuxt.config.ts

[DEV-11620](https://app.clickup.com/t/2645698/DEV-11620)
Use new domain for indexer.

feat: update indexer endpoint to new domain

---

components/AssetLinks.vue
components/CollectionView.vue
components/ProfileCard.vue
components/__tests__/__snapshots__/AssetLinks.spec.ts.snap
components/__tests__/__snapshots__/ProfileCard.spec.ts.snap
domains/graph/components/ProfileAssetsGraph.vue
pages/settings/data-provider/__tests__/__snapshots__/index.spec.ts.snap
pages/settings/data-provider/__tests__/index.spec.ts

[DEV-11616](https://app.clickup.com/t/2645698/DEV-11616)
[DEV-11617](https://app.clickup.com/t/2645698/DEV-11617)
- make separation between social and custom links
- make larger buttons when collection view is in mobile

feat: social links update

---

composables/useFollowingSystem.ts

[DEV-11631](https://app.clickup.com/t/2645698/DEV-11631)

fix: problem with follower system when no browser extension is available

---

domains/graph/composables/useProfileGraph.ts

[DEV-11638](https://app.clickup.com/t/2645698/DEV-11638)
Resolve profile link same as in RPC version.

fix: profile link on indexer version

---

components/ModalTemplateFollowers.vue

[DEV-11629](https://app.clickup.com/t/2645698/DEV-11629)

feat: allow right click on the followers

---

domains/graph/components/AppNavbarProfileSearchGraph.vue
domains/rpc/components/AppNavbarProfileSearchRpc.vue
package.json
yarn.lock

[DEV-11624](https://app.clickup.com/t/2645698/DEV-11624)
- prevent double requests on search (input click)
- clear search on `Escape` key

fix: clear search on escape

---

domains/graph/components/ProfileViewGraph.vue

[DEV-11646](https://app.clickup.com/t/2645698/DEV-11646)

fix: change default filters

---

components/AppNavbarLanding.vue
translations/en_US.json

[DEV-11611](https://app.clickup.com/t/2645698/DEV-11611)

feat: support link changes

---

composables/useFilters.ts

[DEV-11630](https://app.clickup.com/t/2645698/DEV-11630)

feat: replace url when changing filters

---

components/AppModal.vue
components/FollowCounters.vue
components/ModalTemplateFollowers.vue
composables/useModal.ts
types/modal.ts

[DEV-11644](https://app.clickup.com/t/2645698/DEV-11644)
Allow to use back button to re-open follower system modals.

feat: url based modal for follower system

---

composables/useNetworkConfig.ts

[DEV-11666](https://app.clickup.com/t/2645698/DEV-11666)

feat: use same follower system contract address for Testnet and Mainnet

---

nuxt.config.ts

[DEV-11667](https://app.clickup.com/t/2645698/DEV-11667)

feat: change indexer domain

---

app.vue
components/FollowList.vue
components/ModalTemplateMobileSearch.vue
domains/graph/components/AppNavbarProfileSearchGraph.vue
domains/graph/components/ProfileAssetsGraph.vue
domains/graph/components/SendCardProfileSearchGraph.vue
domains/rpc/components/AppNavbarProfileSearchRpc.vue
package.json
yarn.lock

[DEV-11674](https://app.clickup.com/t/2645698/DEV-11674)
- fix web3 error on page reload when modal was open
- fix search field issue when fast typing
- make "Escape" clear as built in web component functionality

fix: search issues

---

components/ModalTemplateSelectAssets.vue
domains/graph/composables/useProfileHoldsGraph.ts
translations/en_US.json

[DEV-11679](https://app.clickup.com/t/2645698/DEV-11679)
Display missing LSP8 collectibles in send modal.

fix: display LSP8 collectibles in send screen

---

components/ProfileCardShareLink.vue

[DEV-11672](https://app.clickup.com/t/2645698/DEV-11672)

fix: track isResolved flag to recalculate link width

---

components/AssetImage.vue
types/asset.ts
types/image.ts
utils/getImages.ts

[DEV-11394](https://app.clickup.com/t/2645698/DEV-11394)

refactor: use image statuses from indexer

---

utils/__tests__/hexToNumber.spec.ts
utils/__tests__/hexToUtf8.spec.ts
utils/decodeParameter.ts
utils/hexToNumber.ts
utils/hexToUtf8.ts
utils/toChecksumAddress.ts

N/A
Makes less important errors as warnings.

chore: use warnings instead of errors

---

components/ModalTemplateMobileSearch.vue
domains/graph/components/AppNavbarProfileSearchGraph.vue
domains/graph/components/SendCardProfileSearchGraph.vue
domains/rpc/components/AppNavbarProfileSearchRpc.vue
domains/rpc/components/SendCardProfileSearchRpc.vue
package.json
yarn.lock

[DEV-11694](https://app.clickup.com/t/2645698/DEV-11694)
- fix issue when search value show `undefined`
- fix search escape key reset while value debounce is running (needs web component update)

fix: debounce issue on search clear

---

queries/profileAssetsQuery.gql

[DEV-11696](https://app.clickup.com/t/2645698/DEV-11696)

fix: duplicated assets

---

domains/graph/components/ProfileShowcaseGraph.vue
queries/profileShowcaseQuery.gql

[DEV-11673](https://app.clickup.com/t/2645698/DEV-11673)
- show profiles that have at least 5 followers
- show profiles that are created more then 2 hours ago

feat: update profile showcase criteria

---

components/GridView.vue
components/GridWidget.vue
components/GridWidgetIframe.vue
translations/en_US.json

* use dynamic components instead of v-ifs
* Added iframe component with small warning 
* Improved layout responsiveness

feat: the grid more improvements

---

components/GridView.vue
utils/__tests__/gridLayout.spec.ts
utils/gridLayout.ts

* fix toGridLayoutItems for 1 grid column
* update grid responsiveness - bypass library responsiveness

feat: the grid fix responsiveness

---

translations/en_US.json

[DEV-11716](https://app.clickup.com/t/2645698/DEV-11716)

fix: commonground label

---

components/ProfileInfo.vue

[DEV-11709](https://app.clickup.com/t/2645698/DEV-11709)
- show `0` instead of `undefined` when profile count is fetched
- format number based on locale
- fix issue when number didn't update when switching networks

fix: profile count show `undefined` when loading

---

components/SendCardDraft.vue
domains/graph/composables/useAssetGraph.ts
queries/assetQuery.gql

[DEV-11681](https://app.clickup.com/t/2645698/DEV-11681)
Fixes check for tokenId in indexer version that caused the modal to show up.

fix: missing asset issue

---

components/GridView.vue
components/ModalGridDebug.vue
types/grid.ts
utils/gridLayout.ts

- replaced event listener for resize observer
- Simplified edit controls, only allow drag from handle
- Refactored grid debug modal
- remove unused ref

feat the grid improvements 3

---

components/AppPlaceholderSection.vue
components/AssetAddress.vue
components/AssetLinks.vue
components/FollowButton.vue
components/FollowList.vue
components/TokenListCardLyx.vue
components/__tests__/__snapshots__/AssetAddress.spec.ts.snap
components/__tests__/__snapshots__/AssetDescription.spec.ts.snap
components/__tests__/__snapshots__/AssetLinks.spec.ts.snap
domains/graph/components/CollectionViewGraph.vue
domains/graph/components/NftListCardCreatorsGraph.vue
domains/graph/components/NftListCardGraph.vue
domains/graph/components/ProfileAssetsGraph.vue
domains/graph/components/TokenListCardGraph.vue
domains/graph/components/TokenListGraph.vue
domains/graph/components/__tests__/__snapshots__/AssetCreatorsGraph.spec.ts.snap
domains/graph/components/__tests__/__snapshots__/NftListCardCreatorsGraph.spec.ts.snap
domains/rpc/components/NftListCardCreatorsRpc.vue
domains/rpc/components/NftListCardRpc.vue
domains/rpc/components/TokenListCardRpc.vue
domains/rpc/components/TokenListRpc.vue

[DEV-11729](https://app.clickup.com/t/2645698/DEV-11729)

fix: issues in small mobile screens

---

components/GridConfirmationDialog.vue
components/GridView.vue
components/GridWidgetImage.vue
components/GridWidgetText.vue
domains/graph/composables/useProfileAssetsGraph.ts
stores/app.ts
translations/en_US.json
types/grid.ts
utils/gridConfig.ts
utils/gridLayout.ts

[DEV-11730](https://app.clickup.com/t/2645698/DEV-11730)
- persist edited state upon reload
- add confirmation dialog
- editing only allowed for own profile and when connected

feat: persist grid config

---

domains/grid/components/GridWidgetText.vue
domains/grid/components/GridWidgetTitleLink.vue

Fix issue where widget background color wasn't displayed correctly.

fix: background color issue

---

domains/grid/shared/config.ts
domains/grid/utils/__tests__/gridWidget.spec.ts
domains/grid/utils/gridWidget.ts

DEV-11746
Adds function to parse user input for different platforms.
This pr adds support for youtube and x, more platforms in follow up prs

feat: Add widget input parser functions for x and youtube

---

domains/grid/shared/config.ts
domains/grid/utils/__tests__/gridWidget.spec.ts
domains/grid/utils/gridWidget.ts

DEV-11746
Added Spotify and Soundcloud as supported platforms for input parsing

feat: the grid input parser platforms SoundCloud + Spotify

---

domains/grid/shared/config.ts
domains/grid/utils/__tests__/gridParser.spec.ts
domains/grid/utils/gridParser.ts

DEV-11799
Update Instagram widget parameters regex parsing

fix: instagram regex

---

domains/grid/composables/useGrid.ts
domains/grid/utils/__tests__/gridLayout.spec.ts
domains/grid/utils/gridLayout.ts
types/grid.ts

refactor: Grid layout handling

---

components/AppNavbarMobileSearch.vue
package.json
yarn.lock

[DEV-11764](https://app.clickup.com/t/2645698/DEV-11764)

feat: change modal overlay color

---

domains/grid/components/GridWidget.vue
package.json
yarn.lock

[DEV-11806](https://app.clickup.com/t/2645698/DEV-11806)

feat: new resize handle

---

components/ProfileTabs.vue
domains/grid/components/GridView.vue
domains/grid/composables/useGrid.ts
domains/grid/utils/__tests__/compareLayouts.spec.ts
domains/grid/utils/compareLayouts.ts
types/grid.ts
utils/__tests__/deepEqual.spec.ts
utils/deepEqual.ts

[DEV-11818](https://app.clickup.com/t/2645698/DEV-11818)

feat: better dirty state check

---

domains/grid/components/GridWidget.vue

[DEV-11839](https://app.clickup.com/t/2645698/DEV-11839)

fix: empty dropdown issue

---

domains/grid/components/GridView.vue
domains/grid/shared/config.ts
stores/grid.ts

[DEV-11841](https://app.clickup.com/t/2645698/DEV-11841)

feat: calculate row height

---

domains/grid/components/GridConfirmationDialog.vue
domains/grid/components/GridView.vue
domains/grid/shared/config.ts

[DEV-11846](https://app.clickup.com/t/2645698/DEV-11846)

feat: widget move animation

---

domains/grid/utils/__tests__/gridParser.spec.ts
domains/grid/utils/gridParser.ts

DEV-11779
Add support for spotify theme.
Use named capturing groups for better regex readability

feat: better spotify parameters parsing

---

domains/grid/components/AddWidgetText.vue

[DEV-11877](https://app.clickup.com/t/2645698/DEV-11877)

feat: optional description in Text widget

---

domains/grid/components/AddWidgetText.vue

[DEV-11878](https://app.clickup.com/t/2645698/DEV-11878)

feat: change field order in Text widget

---

domains/grid/components/GridWidget.vue

[DEV-11899](https://app.clickup.com/t/2645698/DEV-11899)

Lazy load widgets

---

components/ProfileView.vue

[DEV-11975](https://app.clickup.com/t/2645698/DEV-11975)

fix: long grid issue

---

.editorconfig
biome.json

N/A
Adding same line width in all configs fix code shift in debug mode.

chore: unify line width

---

domains/grid/components/GridWidgetText.vue

[DEV-11990](https://app.clickup.com/t/2645698/DEV-11990)

feat: allow multiline in text widget

---

components/ProfileView.vue
domains/grid/components/GridView.vue
domains/grid/components/GridWidgetAddContent.vue
domains/grid/composables/useGrid.ts
domains/grid/shared/config.ts

[DEV-11979](https://app.clickup.com/t/2645698/DEV-11979)

feat: empty grid

---

domains/grid/platform-parser/__tests__/warpcastParser.spec.ts
domains/grid/platform-parser/warpcastParser.ts

feat: warpcast input parser updates

---

domains/grid/components/GridFloatingMenu.vue
domains/grid/components/__tests__/__snapshots__/GridFloatingMenu.spec.ts.snap

[DEV-11940](https://app.clickup.com/t/2645698/DEV-11940)

feat: swap buttons in floating menu

---

domains/grid/components/GridView.vue

[DEV-12045](https://app.clickup.com/t/2645698/DEV-12045)

fix: reset button clear whole grid instead of bringing user to initial state

---

domains/grid/composables/useGrid.ts

[DEV-12058](https://app.clickup.com/t/2645698/DEV-12058)

fix: add widget position

---

composables/useWeb3.ts
domains/grid/utils/gridConfig.ts

[DEV-12059](https://app.clickup.com/t/2645698/DEV-12059)

fix: grid save on mobile 

---

domains/grid/components/GridFloatingMenu.vue

[DEV-11981](https://app.clickup.com/t/2645698/DEV-11981)

feat: menu in middle of the screen

---

domains/grid/components/GridView.vue

[DEV-12078](https://app.clickup.com/t/2645698/DEV-12078)

fix: user sees "add content" placeholder when not connected

---

domains/grid/platform-parser/__tests__/spotifyParser.spec.ts
domains/grid/platform-parser/spotifyParser.ts

[DEV-12080](https://app.clickup.com/t/2645698/DEV-12080)

feat: add support for Spotify `show` and `episode` type

---

README.md
app.vue
composables/web3-provider/useWalletConnectProvider.ts
nuxt.config.ts
package.json
shared/config.ts
site.meta.json
yarn.lock

[DEV-12077](https://app.clickup.com/t/2645698/DEV-12077)

feat: rename `universalprofile` to `universaleverything`

---

app.vue
components/AppModal.vue

[DEV-12060](https://app.clickup.com/t/2645698/DEV-12060)

fix: auto resize modal

---

nuxt.config.ts
package.json
server/middleware/redirect.ts

[DEV-12077](https://app.clickup.com/t/2645698/DEV-12077)
Redirect middleware

feat: Redirect middleware
